; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon May 30 2022 14:35:59 GMT-0500 (Central Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


