; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon May 30 2022 14:36:02 GMT-0500 (Central Daylight Time)

