; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon May 30 2022 14:36:02 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0

